### ISSUE TITLE
Peer to peer review session

### ISSUE THREAD

**Issue by teekaytech** [teekaytech/Weather-App#2]
Hello guys, 

You feedbacks are highly welcome :blush: 

Thank you in advance.

**Comment by mariosknl** [comment]
Great project Taofeek. I really liked how well your project is structured. Nice way to catch the error

**Comment by kubilaycaglayan** [comment]
Hello Taofeek :wave: 
Thanks for the presentation!

Two things I can comment on:

1. You can add  a min-width attribute to your cards to protect them against overflowing. Also, under a certain width, say like 600 px, you can add a media query to center your elements. This way your web page will be mobile compatible :blush: 

2. I think you don't need the setTimeout function to always show the spinner, anymore :angel: 

With all my respect...
